trigger: none
pr: none

variables:
- name: hostedVmImage
  value: 'ubuntu-20.04'

stages:
- stage: One
  dependsOn: []
  displayName: One
  jobs:
    - job: one
      displayName: One
      pool:
        vmImage: $(hostedVmImage)
      steps:
        - script: |
            echo "One complete"
- stage: Two
  dependsOn: []
  displayName: Two
  jobs:
    - job: two
      displayName: Two
      pool:
        vmImage: $(hostedVmImage)
      steps:
        - script: |
            echo "Two complete"
            exit 1
- stage: Three
  dependsOn: 
  - One
  - Two
  displayName: Three
  jobs:
    - job: three
      displayName: Three
      pool:
        vmImage: $(hostedVmImage)
      steps:
        - script: |
            echo "Three complete"